webapp/solver/urls.py
from django.urls import include, path, re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.solver, name='solver'),
]

webapp/webapp/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from solver import views

urlpatterns = [
    re_path(r'^', include('solver.urls')),
    path('admin/', admin.site.urls),
]

webapp/solver/models.py
from django.db import models

# Create your models here.

webapp/solver/forms.py
from django import forms

class EquForm(forms.Form):
	equation = forms.CharField(widget=forms.TextInput(attrs={'max_length' : 1000, 'class' : 'form-control', 'required' : True}))

webapp/solver/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .computorV1 import computor
from .forms import EquForm


def index(request):
    return render(request, 'solver/index.html')


def solver(request):
    if request.method == 'POST':
        form = EquForm(request.POST)
        if form.is_valid():
            solution = computor.solve_equ(form.cleaned_data['equation'])
            solution = solution.split('\n')
            return render(
                request,
                'solver/solution.html',
                {'content': solution}
            )
    else:
        form = EquForm()
    return render(request, 'solver/solver.html', {'form': form})

webapp/solver/templates/solver/solution.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<title>Computor V1 - Solution</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
		<style>
			h1 {
				margin-bottom: 50px;
			}
			.output {
				font-size: 20px;
				margin: auto;
				max-width: 550px;
				text-align: left;
			    width: 50%;
			}
		</style>
	</head>
	<body>
		<div class="container-fluid">
	      <div class="row">
	        <div class="col-lg-12 text-center">
	        	<h1 class="mt-5">Computor V1</h1>
				{% block content %}
					{% for line in content %}
			        	<p class="output">{{ line }}</p>
					{% endfor %}
				{% endblock %}
				<a class="btn btn-danger" href="/" role="button">Back</a>
	        </div>
	      </div>
	</div>
	</body>
</html>

webapp/solver/templates/solver/solver.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<title>Computor V1 - Solver</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
		<style type="text/css">
			#id_equation {
				max-width: 600px;
				margin: auto;
			}
		</style>
	</head>
	<body>
		<div class="container-fluid">
	      <div class="row">
	        <div class="col-12 text-center">
	          <h1 class="mt-5">Computor V1</h1>
	          <p class="lead">Solve a polynomial equation up to degree 2</p>
			  <p class="lead">Format: n * X^[0-2]</p>
			  <form action="/" method="post">
				  <div class="form-group">
					  {% csrf_token %}
				      {{ form }}
				  </div>
				  <input type="submit" class="btn btn-danger" value="Solve"/>
			  </form>
		  	</div>
	      </div>
	</div>
	</body>
</html>